// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/babon21/excel-offer-storage/internal/offer/domain"
	mock "github.com/stretchr/testify/mock"
)

// OfferReader is an autogenerated mock type for the OfferReader type
type OfferReader struct {
	mock.Mock
}

// ReadAll provides a mock function with given fields: filePath
func (_m *OfferReader) ReadAll(filePath string) ([]domain.Offer, uint32, error) {
	ret := _m.Called(filePath)

	var r0 []domain.Offer
	if rf, ok := ret.Get(0).(func(string) []domain.Offer); ok {
		r0 = rf(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Offer)
		}
	}

	var r1 uint32
	if rf, ok := ret.Get(1).(func(string) uint32); ok {
		r1 = rf(filePath)
	} else {
		r1 = ret.Get(1).(uint32)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(filePath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
