// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OfferGateway is an autogenerated mock type for the OfferGateway type
type OfferGateway struct {
	mock.Mock
}

// DeleteOffers provides a mock function with given fields: filename
func (_m *OfferGateway) DeleteOffers(filename string) {
	_m.Called(filename)
}

// DownloadOffers provides a mock function with given fields: url
func (_m *OfferGateway) DownloadOffers(url string) (string, error) {
	ret := _m.Called(url)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
